### PR TITLE
README Updates

### PR DESCRIPTION
**Pull request by BrandonDudek**
Created New Computer Setup README

Updated Java Training README

### CODE REVIEW

**Comment by MathNerd28** [comment]
We should consider just making a Java-Training repo, unless there's a purpose in keeping this next to robot code

**Comment by KE-Holtz** [comment]
I agree with Xander, other than maybe some reference material I think this would be better separated, especially since it doesn't necessarily pertain to robot code

**Comment by BrandonDudek** [comment]
The idea was to make it easy to maintain. If we create a repo with just java docs, I think it will quickly get forgotten.

**Comment by mmarchetti** [comment]
We have a lot of forgotten repos already, so I'm inclined to agree with @BrandonDudek here. But, I don't feel strongly about it and am ok with this being a student lead decision.

**Review by KE-Holtz — APPROVED** [review]

**Pull request merged**
